### ISSUE TITLE
Coverage

### ISSUE THREAD

**Issue by parland** [arcada-uas/TechLabs-Docs#1]
We need to define what belongs to TL-Docs. Is it only the website, or should we also include NextCloud, Onboarding, hardware, botnet, etc.?

**Comment by thesourmango** [comment]
Man you are fast, minutes after init! Kristoffer is moving over the content from Collectives to the Docs, so this repo is for hosting a public wiki for TechLabs. 

Each project has it's own README and larger projects like the website might have their own "developer" wikis. 
The target audience of TechLabs-Docs is all members of TechLabs, since our nextcloud now has a direct link here in the main menu instead of the previously hosted Collectives app.
